const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const { test } = require('node:test');
const { runInNewContext } = require('node:vm');

const source = readFileSync(`${__dirname}/../web/pwa_viewport.js`, 'utf8');

function eventTarget(fields = {}) {
  const listeners = new Map();
  return Object.assign(fields, {
    addEventListener(name, listener) {
      if (!listeners.has(name)) listeners.set(name, []);
      listeners.get(name).push(listener);
    },
    emit(name) {
      for (const listener of listeners.get(name) ?? []) listener();
    },
  });
}

function createPage({ ios = true, standalone = true, legacy = false,
  scrollY = 62, scale = 1, activeElement = null, viewport = true } = {}) {
  const frames = [];
  const scrolls = [];
  const document = eventTarget({ visibilityState: 'visible', activeElement });
  const window = eventTarget({
    history: { scrollRestoration: 'auto' },
    visualViewport: viewport ? eventTarget({ scale }) : undefined,
    scrollX: 0,
    scrollY,
    matchMedia: () => ({ matches: standalone }),
    requestAnimationFrame: (callback) => frames.push(callback),
    scrollTo(x, y) {
      scrolls.push([x, y]);
      window.scrollX = x;
      window.scrollY = y;
      window.emit('scroll');
    },
  });
  const navigator = {
    userAgent: ios ? 'iPhone' : 'Android',
    standalone: legacy,
  };
  runInNewContext(source, { window, document, navigator });
  return { window, document, scrolls, flush() {
    // Process one frame, leaving events generated by scrollTo for the next.
    for (const callback of frames.splice(0)) callback();
  } };
}

test('repairs the observed 62px offset on cold start without a reload', () => {
  const page = createPage();
  assert.equal(page.window.history.scrollRestoration, 'manual');
  assert.equal(page.window.scrollY, 0);
  assert.deepEqual(page.scrolls, [[0, 0]]);
  page.flush();
  assert.equal(page.scrolls.length, 1);
});

for (const trigger of ['pageshow', 'focus', 'visibilitychange', 'scroll',
  'viewport-scroll', 'viewport-resize']) {
  test(`recovers a later offset after ${trigger}`, () => {
    const page = createPage({ scrollY: 0 });
    page.flush();
    page.window.scrollY = 62;
    if (trigger.startsWith('viewport-')) {
      page.window.visualViewport.emit(trigger.slice(9));
    } else {
      (trigger === 'visibilitychange' ? page.document : page.window).emit(trigger);
    }
    page.flush();
    assert.equal(page.window.scrollY, 0);
  });
}

test('leaves text entry alone, then recovers after the field loses focus', () => {
  // Flutter may place its editor inside a shadow root.
  const activeElement = { shadowRoot: {
    activeElement: { matches: () => true },
  } };
  const page = createPage({ activeElement });
  page.flush();
  assert.equal(page.window.scrollY, 62);
  page.document.activeElement = null;
  page.document.emit('focusout');
  page.flush();
  assert.equal(page.window.scrollY, 0);
});

test('leaves contenteditable focus and zoom panning alone', () => {
  const editing = createPage({ activeElement: {
    matches: () => false, isContentEditable: true,
  } });
  editing.flush();
  assert.equal(editing.window.scrollY, 62);
  const zoomed = createPage({ scale: 2 });
  zoomed.flush();
  assert.equal(zoomed.window.scrollY, 62);
  zoomed.window.visualViewport.scale = 1;
  zoomed.window.visualViewport.emit('resize');
  zoomed.flush();
  assert.equal(zoomed.window.scrollY, 0);
});

test('defers recovery until the document becomes visible', () => {
  const page = createPage({ scrollY: 0 });
  page.flush();
  page.document.visibilityState = 'hidden';
  page.window.scrollY = 62;
  page.document.emit('visibilitychange');
  page.flush();
  assert.equal(page.window.scrollY, 62);
  page.document.visibilityState = 'visible';
  page.document.emit('visibilitychange');
  page.flush();
  assert.equal(page.window.scrollY, 0);
});

test('does not affect Safari tabs or non-iOS PWAs', () => {
  for (const options of [{ standalone: false }, { ios: false }]) {
    const page = createPage(options);
    page.window.emit('pageshow');
    page.flush();
    assert.equal(page.window.scrollY, 62);
    assert.equal(page.window.history.scrollRestoration, 'auto');
  }
});

test('supports legacy standalone detection without VisualViewport', () => {
  const page = createPage({ standalone: false, legacy: true, viewport: false });
  assert.equal(page.window.scrollY, 0);
});

test('coalesces viewport events without a recurring scroll loop', () => {
  const page = createPage({ scrollY: 0 });
  page.flush();
  page.window.scrollX = 8;
  page.window.scrollY = 62;
  for (let i = 0; i < 10; i++) page.window.visualViewport.emit('scroll');
  page.flush();
  page.flush();
  assert.deepEqual(page.scrolls, [[0, 0]]);
});
