// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFKR5xGOFwOgRPaA1haaeZwLP8bncFkm0',
    appId: '1:701824546350:web:3c3a7d84fc778ce71691bf',
    messagingSenderId: '701824546350',
    projectId: 'musi-link-e7759',
    authDomain: 'musi-link-e7759.firebaseapp.com',
    storageBucket: 'musi-link-e7759.firebasestorage.app',
    measurementId: 'G-GBEJYW3D0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYg90AayN-DcpaT98oNykHijMczanhZg8',
    appId: '1:701824546350:android:4f63c964c25d52fa1691bf',
    messagingSenderId: '701824546350',
    projectId: 'musi-link-e7759',
    storageBucket: 'musi-link-e7759.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBez2oorhb-9d_eRSUHVKSaQYoFjuWf1Co',
    appId: '1:701824546350:ios:c86b1f00c0da1f701691bf',
    messagingSenderId: '701824546350',
    projectId: 'musi-link-e7759',
    storageBucket: 'musi-link-e7759.firebasestorage.app',
    iosBundleId: 'app.musilink',
  );
}
